;;; ========== GENERAL SETTINGS =================

;; Start at HOME directory
(setq initial-buffer-choice "~")

;; Disable tool-bar and menu-bar
(tool-bar-mode -1)
(menu-bar-mode -1)

;; Disable splash screen and startup message
(setq inhibit-startup-message t) 
(setq initial-scratch-message nil)

;; Quality of life settings
(global-display-line-numbers-mode t)
(display-line-numbers-mode t)			     
(show-paren-mode t)

;; Backup-files settings
(setq make-backup-files nil)

;; Disable autosave mode
(setq auto-save-default nil)

;; Disable beeping sound on windows
(setq visible-bell t)

;; Replace highlighted text with what I type
(delete-selection-mode t)

;; Disable creation of #files when editing something
(setq create-lockfiles nil)

;;Ido mode
(ido-mode t)
(ido-everywhere t)

;;; ========== LOADING CONFIGS =================

(load "~/.emacs.d/packages.el")
(load "~/.emacs.d/theme.el")
(load "~/.emacs.d/lsp.el")

;;; ========== AUTOGENERATED CONFIGURATIONS =================

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(jka-compr-compression-info-list
   '(["\\.Z\\'" "compressing" "compress"
      ("-c")
      "uncompressing" "gzip"
      ("-c" "-q" "-d")
      nil t "\37\235" zlib-decompress-region]
     ["\\.bz2\\'" "bzip2ing" "bzip2" nil "bunzip2ing" "bzip2"
      ("-d")
      nil t "BZh" nil]
     ["\\.tbz2?\\'" "bzip2ing" "bzip2" nil "bunzip2ing" "bzip2"
      ("-d")
      nil nil "BZh" nil]
     ["\\.\\(?:tgz\\|svgz\\|sifz\\)\\'" "compressing" "gzip"
      ("-c" "-q")
      "uncompressing" "gzip"
      ("-c" "-q" "-d")
      t nil "\37\213" zlib-decompress-region]
     ["\\.g?z\\'" "compressing" "gzip"
      ("-c" "-q")
      "uncompressing" "gzip"
      ("-c" "-q" "-d")
      t t "\37\213" zlib-decompress-region]
     ["\\.lz\\'" "Lzip compressing" "lzip"
      ("-c" "-q")
      "Lzip uncompressing" "lzip"
      ("-c" "-q" "-d")
      t t "LZIP" nil]
     ["\\.lzma\\'" "LZMA compressing" "lzma"
      ("-c" "-q" "-z")
      "LZMA uncompressing" "lzma"
      ("-c" "-q" "-d")
      t t "" nil]
     ["\\.xz\\'" "XZ compressing" "xz"
      ("-c" "-q")
      "XZ uncompressing" "xz"
      ("-c" "-q" "-d")
      t t "\3757zXZ\0" nil]
     ["\\.txz\\'" "XZ compressing" "xz"
      ("-c" "-q")
      "XZ uncompressing" "xz"
      ("-c" "-q" "-d")
      t nil "\3757zXZ\0" nil]
     ["\\.dz\\'" nil "C:\\Program Files\\7-Zip\\7z.exe" nil "uncompressing" "C:\\Program Files\\7-Zip\\7z.exe"
      ("-c" "-q" "-d")
      nil t "\37\213" nil]
     ["\\.zst\\'" "zstd compressing" "zstd"
      ("-c" "-q")
      "zstd uncompressing" "zstd"
      ("-c" "-q" "-d")
      t t "(\265/\375" nil]
     ["\\.tzst\\'" "zstd compressing" "zstd"
      ("-c" "-q")
      "zstd uncompressing" "zstd"
      ("-c" "-q" "-d")
      t nil "(\265/\375" nil])))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
